import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';

const OutputPage = () => {
  const navigate = useNavigate();
  const [researchData, setResearchData] = useState(null);
  const [isGenerating, setIsGenerating] = useState(true);
  const [progress, setProgress] = useState(0);

  useEffect(() => {
    const storedData = localStorage.getItem('researchData');
    if (storedData) {
      setResearchData(JSON.parse(storedData));
    } else {
      navigate('/');
    }

    // Simulate research generation
    const interval = setInterval(() => {
      setProgress(prev => {
        if (prev >= 100) {
          clearInterval(interval);
          setIsGenerating(false);
          return 100;
        }
        return prev + 10;
      });
    }, 500);

    return () => clearInterval(interval);
  }, [navigate]);

  const handleNewResearch = () => {
    localStorage.removeItem('researchData');
    navigate('/');
  };

  const handleDownload = () => {
    // This will be integrated with your FastAPI backend
    alert('Download feature will be integrated with FastAPI backend');
  };

  if (!researchData) {
    return <div>Loading...</div>;
  }

  // Mock generated data
  const mockSummary = `
    Based on comprehensive analysis of ${researchData.numberOfSources} sources from the past ${researchData.timeRange} days, 
    our research reveals significant trends in the requested domain. Key findings indicate a 45% increase in market adoption, 
    with emerging technologies driving innovation across multiple sectors. The competitive landscape shows established players 
    maintaining market leadership while new entrants disrupt traditional business models through innovative approaches.
  `;

  const mockSources = [
    { name: 'TechCrunch', relevance: 95, type: 'Technology News' },
    { name: 'Harvard Business Review', relevance: 92, type: 'Academic Journal' },
    { name: 'Market Research Inc.', relevance: 88, type: 'Market Analysis' },
    { name: 'Industry Weekly', relevance: 85, type: 'Trade Publication' },
    { name: 'Global Insights', relevance: 82, type: 'Research Firm' },
    { name: 'Innovation Lab', relevance: 78, type: 'Think Tank' },
    { name: 'Data Science Quarterly', relevance: 75, type: 'Academic Journal' },
    { name: 'Future Trends', relevance: 72, type: 'Industry Report' },
    { name: 'Business Analytics', relevance: 68, type: 'Business Publication' },
    { name: 'Tech Innovation', relevance: 65, type: 'Technology Blog' }
  ];

  return (
    <div className="dark-container" style={{ padding: '40px' }}>
      {/* Header */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '30px' }}>
        <div>
          <h1 className="glow-text" style={{ fontSize: '36px', margin: 0 }}>
            Research Report
          </h1>
          <p style={{ color: 'rgba(255, 255, 255, 0.7)', marginTop: '5px' }}>
            Generated by NOVA Intelligence Platform
          </p>
        </div>
        <div style={{ display: 'flex', gap: '10px' }}>
          <button className="btn-secondary" onClick={handleNewResearch}>
            New Research
          </button>
          <button className="btn-primary" onClick={handleDownload}>
            Download {researchData.outputFormat.toUpperCase()}
          </button>
        </div>
      </div>

      {/* Generation Progress */}
      {isGenerating && (
        <div className="card" style={{ marginBottom: '30px' }}>
          <h3 style={{ color: '#9333ea', marginBottom: '15px' }}>Generating Research Report</h3>
          <div style={{ background: 'rgba(255, 255, 255, 0.1)', borderRadius: '8px', height: '20px', overflow: 'hidden' }}>
            <div 
              style={{ 
                background: 'linear-gradient(90deg, #9333ea, #a855f7)', 
                height: '100%', 
                width: `${progress}%`,
                transition: 'width 0.5s ease'
              }}
            />
          </div>
          <p style={{ marginTop: '10px', color: 'rgba(255, 255, 255, 0.7)' }}>
            {progress}% complete - Analyzing sources and generating insights...
          </p>
        </div>
      )}

      {/* Research Metadata */}
      <div className="card" style={{ marginBottom: '30px' }}>
        <h3 style={{ color: '#9333ea', marginBottom: '15px' }}>Research Details</h3>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '15px' }}>
          <div>
            <strong style={{ color: 'rgba(255, 255, 255, 0.8)' }}>Query:</strong>
            <p style={{ color: 'rgba(255, 255, 255, 0.6)' }}>{researchData.query || 'Custom research query'}</p>
          </div>
          <div>
            <strong style={{ color: 'rgba(255, 255, 255, 0.8)' }}>Time Range:</strong>
            <p style={{ color: 'rgba(255, 255, 255, 0.6)' }}>Last {researchData.timeRange} days</p>
          </div>
          <div>
            <strong style={{ color: 'rgba(255, 255, 255, 0.8)' }}>Report Length:</strong>
            <p style={{ color: 'rgba(255, 255, 255, 0.6)' }}>{researchData.reportLength}</p>
          </div>
          <div>
            <strong style={{ color: 'rgba(255, 255, 255, 0.8)' }}>Sources Analyzed:</strong>
            <p style={{ color: 'rgba(255, 255, 255, 0.6)' }}>{researchData.numberOfSources}</p>
          </div>
          <div>
            <strong style={{ color: 'rgba(255, 255, 255, 0.8)' }}>Output Format:</strong>
            <p style={{ color: 'rgba(255, 255, 255, 0.6)' }}>{researchData.outputFormat.toUpperCase()}</p>
          </div>
          <div>
            <strong style={{ color: 'rgba(255, 255, 255, 0.8)' }}>Generated:</strong>
            <p style={{ color: 'rgba(255, 255, 255, 0.6)' }}>
              {new Date(researchData.timestamp).toLocaleString()}
            </p>
          </div>
        </div>
        
        {researchData.keywords.length > 0 && (
          <div style={{ marginTop: '15px' }}>
            <strong style={{ color: 'rgba(255, 255, 255, 0.8)' }}>Keywords:</strong>
            <div style={{ marginTop: '5px' }}>
              {researchData.keywords.map((keyword, index) => (
                <span key={index} className="keyword-tag">
                  {keyword}
                </span>
              ))}
            </div>
          </div>
        )}
      </div>

      {/* Executive Summary */}
      <div className="card" style={{ marginBottom: '30px' }}>
        <h3 style={{ color: '#9333ea', marginBottom: '15px' }}>Executive Summary</h3>
        <div style={{ lineHeight: '1.6', color: 'rgba(255, 255, 255, 0.8)' }}>
          {mockSummary}
        </div>
      </div>

      {/* Sources */}
      <div className="card" style={{ marginBottom: '30px' }}>
        <h3 style={{ color: '#9333ea', marginBottom: '15px' }}>
          Sources Analyzed ({mockSources.length})
        </h3>
        <div style={{ display: 'grid', gap: '10px' }}>
          {mockSources.map((source, index) => (
            <div 
              key={index} 
              style={{ 
                display: 'flex', 
                justifyContent: 'space-between', 
                alignItems: 'center',
                padding: '12px',
                background: 'rgba(147, 51, 234, 0.1)',
                borderLeft: '3px solid #9333ea',
                borderRadius: '4px'
              }}
            >
              <div>
                <strong style={{ color: 'rgba(255, 255, 255, 0.9)' }}>{source.name}</strong>
                <span style={{ color: 'rgba(255, 255, 255, 0.6)', marginLeft: '10px', fontSize: '12px' }}>
                  {source.type}
                </span>
              </div>
              <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                <div style={{ 
                  width: '100px', 
                  height: '6px', 
                  background: 'rgba(255, 255, 255, 0.1)', 
                  borderRadius: '3px',
                  overflow: 'hidden'
                }}>
                  <div 
                    style={{ 
                      width: `${source.relevance}%`, 
                      height: '100%', 
                      background: source.relevance > 80 ? '#10b981' : source.relevance > 60 ? '#f59e0b' : '#ef4444'
                    }}
                  />
                </div>
                <span style={{ color: 'rgba(255, 255, 255, 0.8)', fontSize: '12px' }}>
                  {source.relevance}%
                </span>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Key Insights */}
      <div className="card">
        <h3 style={{ color: '#9333ea', marginBottom: '15px' }}>Key Insights</h3>
        <div style={{ display: 'grid', gap: '15px' }}>
          <div style={{ padding: '15px', background: 'rgba(147, 51, 234, 0.1)', borderRadius: '8px' }}>
            <h4 style={{ color: '#a855f7', marginBottom: '8px' }}>📈 Market Growth</h4>
            <p style={{ color: 'rgba(255, 255, 255, 0.8)', margin: 0 }}>
              Significant growth trajectory identified with 45% increase in market adoption over the analyzed period.
            </p>
          </div>
          <div style={{ padding: '15px', background: 'rgba(147, 51, 234, 0.1)', borderRadius: '8px' }}>
            <h4 style={{ color: '#a855f7', marginBottom: '8px' }}>🚀 Innovation Trends</h4>
            <p style={{ color: 'rgba(255, 255, 255, 0.8)', margin: 0 }}>
              Emerging technologies are driving disruption across traditional business models.
            </p>
          </div>
          <div style={{ padding: '15px', background: 'rgba(147, 51, 234, 0.1)', borderRadius: '8px' }}>
            <h4 style={{ color: '#a855f7', marginBottom: '8px' }}>🎯 Competitive Landscape</h4>
            <p style={{ color: 'rgba(255, 255, 255, 0.8)', margin: 0 }}>
              Established players maintain leadership while new entrants gain market share through innovation.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default OutputPage;
